# user:password@tcp(localhost:3306)/dbname?charset=utf8&parseTime=True&loc=Local
mysql:
  user: 'root'
  pass: 'root'
  host: 'localhost'
  port: '33060'
  dbname: 'echo'
  debug: true # 打印sql日志

server:
  addr: '127.0.0.1:8000'
  cert: ''
  key: ''
  autoTls: false
  staticDir: './static'
  staticPrefix: '/static'

websocket:
  addr: '0.0.0.0:8001'
  cert: ''
  key: ''

redis:
  addr: 'localhost:6379'